Feature/manatime 11 submit timesheet reminder
ManatiCR/manatime pull request #69
Opened 2016-10-04 00:01 UTC by josue2591

**Steps to test**

- Go to: `/admin/config/manatime/timesheet-reminder`, and see if the form is displayed. Once there save the time the reminders will be sended (The actual time).
- Run the Cron.
- Since the terminal run `vagrant ssh` and go to: `/tmp/devel-mails` once there run l to see if the mails were created succesfully.

**DoD**
- Submit button (form?)
- Set timesheet status to published
- Set time entries to Submitted.
- If submit is done in the middle of a week (ex. wednesday 31 of a given month), create a new timesheet for the rest of the week.

[Issue link](https://github.com/ManatiCR/manatime/issues/17)

2016-10-04 00:16 UTC, josue2591 commented
@kporras07 If you could check this it would be great.

2016-10-04 15:08 UTC, kporras07 requested changes
Besides these comments, it looks like you forgot to featurize the message type "timesheet_reminder"

2016-10-04 15:08 UTC, kporras07 commented on modules/features/manatime_feature_timesheets/manatime_feature_timesheets.module
> +    'description' => 'Add default .',
??

2016-10-04 15:08 UTC, kporras07 commented on modules/features/manatime_feature_timesheets/manatime_feature_timesheets.module
> + * Implements hook_form().
Actually this is not a hook.
Form callback for...

2016-10-04 15:08 UTC, kporras07 commented on modules/features/manatime_feature_timesheets/manatime_feature_timesheets.module
> +  $timezone = 'America/Chicago');
Don't break line if not necessary, it's hard to read.

2016-10-04 15:08 UTC, kporras07 commented on modules/features/manatime_feature_timesheets/manatime_feature_timesheets.module
> +  $actual_day = format_date(REQUEST_TIME, $type = 'custom', $format = 'DHi', $timezone = 'America/Chicago');
Sure you want that timezone?

2016-10-04 15:08 UTC, kporras07 commented on modules/features/manatime_feature_timesheets/manatime_feature_timesheets.module
> +  $current_hour = format_date(REQUEST_TIME, $type = 'custom', $format = 'H', $timezone = 'America/Chicago');
Same here

2016-10-04 15:08 UTC, kporras07 commented on modules/features/manatime_feature_timesheets/manatime_feature_timesheets.module
> +  // Evalutes if it is time to execute the function
Evaluates

2016-10-04 15:08 UTC, kporras07 commented on modules/features/manatime_feature_timesheets/manatime_feature_timesheets.module
> +    $message->field_user = $timesheet->field_user;
Are we really going to use this/

2016-10-04 15:08 UTC, kporras07 commented on modules/features/manatime_feature_timesheets/manatime_feature_timesheets.module
> +    ->propertyCondition('status', 0)
Any chance to get only the latest timesheet per user?

2016-10-05 00:27 UTC, josue2591 commented on modules/features/manatime_feature_timesheets/manatime_feature_timesheets.module
> +    $message->field_user = $timesheet->field_user;
You are right we are not using it.

2016-10-05 12:58 UTC, kporras07 commented on modules/features/manatime_feature_timesheet_reminders/manatime_feature_timesheet_reminders.features.user_permission.inc
> +  $permissions['manage timesheet reminder'] = array(
Could you give this permission to the expected roles? Please

2016-10-05 12:58 UTC, kporras07 commented on modules/features/manatime_feature_timesheets/manatime_feature_timesheets.module
> +    'description' => 'Set the time the timesheet reminder will be sended.',
*will be sent

2016-10-05 13:00 UTC, kporras07 commented on modules/features/manatime_feature_timesheet_reminders/manatime_feature_timesheet_reminders.features.field_instance.inc
> +  $field_instances['message-timesheet_reminder-field_user'] = array(
We don't need this field. Delete it please. (And update the message text so that it uses the message author instead of this field)

2016-10-05 13:01 UTC, kporras07 commented
Almost there!

2016-10-05 17:08 UTC, josue2591 commented
@kporras07 The changes are ready to review.

2016-10-05 18:14 UTC, kporras07 commented
@josue2591 it passes code review. @rohernandez could you do functional review? Please.

2016-10-05 18:16 UTC, rohernandez commented
@kporras07 ok

2016-10-05 18:43 UTC, rohernandez commented
The functional review looks good to me.

2016-10-05 19:50 UTC, kporras07 commented on modules/features/manatime_feature_timesheets/manatime_feature_timesheets.module
> +    $beginning_date = new DateTime('last monday');
Remember there's a possible situation when timesheets don't start on monday: if a timesheet has been previously submitted in that week.  Please change code to take this situatio into account.

2016-10-05 19:53 UTC, kporras07 commented on modules/features/manatime_feature_timesheet_reminders/manatime_feature_timesheet_reminders.features.inc
> +          "value" : "Hello [message:user:name]. \\r\\nWe notice you haven\\u0027t submitted your timesheet this week.\\r\\nWould you be so kind to do it as soon as possible?\\r\\nThank you so much.",
Hello [message:user:name],  (comma instead of period)

2016-10-05 19:53 UTC, kporras07 commented
One last thing: you forgot to enable entity_token, so, message:user:name didn't get replaced

2016-10-05 20:46 UTC, josue2591 commented
@kporras07  ready with the change.

2016-10-05 21:15 UTC, kporras07 approved these changes

2016-10-05 21:16 UTC, kporras07 commented
When Wercker passes, :shipit:

2016-10-05 21:27 UTC, merged