7: Submit timesheet alert.
ManatiCR/manatime pull request #74
Opened 2016-10-18 16:20 UTC by rohernandez

2016-10-19 20:06 UTC, kporras07 requested changes

2016-10-19 20:06 UTC, kporras07 commented on modules/features/manatime_feature_timesheets/manatime_feature_timesheets.module
> +      create_timesheet($title, $beginning->format('Y-m-d H:i:s'), gmdate('Y-m-d H:i:s', $end), $uid);
Rename function

2016-10-19 20:06 UTC, kporras07 commented on modules/features/manatime_feature_timesheets/manatime_feature_timesheets.module
> + * Send an email to each user who have not submitted the timesheet.
who has not submitted the timesheet.

2016-10-19 20:06 UTC, kporras07 commented on modules/features/manatime_feature_timesheets/manatime_feature_timesheets.module
> +  if ($node->status == NODE_NOT_PUBLISHED) {
`===`

2016-10-19 20:06 UTC, kporras07 commented on modules/features/manatime_feature_timesheets/manatime_feature_timesheets.module
> +  if ($node->status == NODE_NOT_PUBLISHED) {
Same here

2016-10-19 20:06 UTC, kporras07 commented on modules/features/manatime_feature_timesheets/plugins/relationships/timesheet_node.inc
> +     * + 576000(seven days in seconds).
Just explain what is 576000.

2016-10-19 20:06 UTC, kporras07 commented on modules/features/manatime_feature_timesheets/plugins/relationships/timesheet_node.inc
> + * @param string $status
Not string.

2016-10-19 20:06 UTC, kporras07 commented on modules/features/manatime_feature_timesheets/plugins/relationships/timesheet_node.inc
> + * @return node
object

2016-10-19 20:06 UTC, kporras07 commented on modules/features/manatime_feature_timesheets/themes/timesheet-view.tpl.php
> +
remove

2016-10-19 23:46 UTC, rohernandez commented on modules/features/manatime_feature_timesheets/manatime_feature_timesheets.module
> +  if ($node->status == NODE_NOT_PUBLISHED) {
The state is a string, '===' does not work.

2016-10-19 23:46 UTC, rohernandez commented on modules/features/manatime_feature_timesheets/manatime_feature_timesheets.module
> +  if ($node->status == NODE_NOT_PUBLISHED) {
The state is a string, '===' does not work.

2016-10-27 22:38 UTC, kporras07 requested changes
Really really minor change.

2016-10-27 22:38 UTC, kporras07 commented on modules/features/manatime_feature_timesheets/manatime_feature_timesheets.module
> +function manatime_create_timesheet($title, $beginning, $end, $uid) {
prefix function with module name please. `manatime_feature_timesheet_create_timesheet`

2016-11-01 16:03 UTC, rohernandez commented
All done.

2017-06-12 22:38 UTC, kporras07 approved these changes

2017-06-12 22:38 UTC, merged